#!/bin/bash -x

{
export IPADDR=$(ip -o -4 addr show eth0 | awk '{ print $4 }' | cut -d/ -f1)
export ETCD_URL="http://$ETCD_NODE_IP:2379"

source /etc/profile.d/proxy.sh
export no_proxy=$no_proxy,$ETCD_NODE_IP
sed -i '/export no_proxy/d' /etc/profile.d/proxy.sh
echo "export no_proxy=$no_proxy" >> /etc/profile.d/proxy.sh
source /etc/profile.d/proxy.sh

yum clean all
yum makecache

# Install Ceph LTS
yum -y erase centos-release-ceph-jewel
yum -y install https://download.ceph.com/rpm-jewel/el7/noarch/ceph-release-1-1.el7.noarch.rpm
yum -y install ceph-common ceph-osd etcd3

# Configure hostname -> IP Key/Value pair in etcd3
etcdctl --endpoints "${ETCD_URL}" set /osd/$(hostname) "${IPADDR}"

# Configure cephman user
useradd cephman
echo "$CEPHMAN_PASSWORD" | passwd cephman --stdin

cat << HERE > /etc/sudoers.d/cephman
Defaults:cephman !requiretty
cephman ALL = (root) NOPASSWD:ALL
HERE
chmod 0440 /etc/sudoers.d/cephman

install -o cephman -g cephman -m 0700 -d /home/cephman/.ssh

echo "$CEPH_SSH_PUB_KEY" > /home/cephman/.ssh/authorized_keys

chown -R cephman.cephman /home/cephman/.ssh
chmod -R 0600 /home/cephman/.ssh/*

## Configure Ceph storage permissions
cat << HERE > /etc/udev/rules.d/99-ceph-journal.rules
KERNEL=="sd[b-z]", SUBSYSTEM=="block", OWNER="ceph", GROUP="disk", MODE="0660"
HERE

udevadm trigger

# Generate /etc/hosts from ceph node registartion in etcd
cat << HERE >/usr/local/bin/etcd-watcher.sh
#!/bin/bash

# Generate /etc/hosts from ceph node registration in etcd
all_nodes=\$(etcdctl --endpoints "${ETCD_URL}" ls --recursive --sort | grep ceph-)

echo -e "# Generated by Heat - \$(date)" > /etc/hosts
echo -e "127.0.0.1\tlocalhost" >> /etc/hosts

for node in \$all_nodes;
do
    node_hostname=\$(echo \$node | cut -d/ -f3)
    node_ip=\$(etcdctl --endpoints "${ETCD_URL}" get \$node)
    echo -e "\$node_ip\t\$node_hostname" >> /etc/hosts
done

HERE

chmod 0500 /usr/local/bin/etcd-watcher.sh

systemctl stop os-collect-config
systemctl disable os-collect-config

$WC_NOTIFY --data-binary '{"status": "SUCCESS", "data": "Server Installation is Complete"}'

} > >(tee /var/log/heat-deployment-$$.log | logger -t user-data -s >/dev/console 2>&1) 2>&1
